/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author abhinavdholi
 */
public class BookingForm extends javax.swing.JFrame {

     Connection con;
    ResultSet rs, rs2;
    Statement stmt, stmt2;
    String conUsername;
    String conPass;
    String userS;
    public BookingForm(String username, String password, String user) {
        initComponents();
        pnlSeats.setVisible(false);
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        try {
            this.conUsername = username;
            this.conPass = password;
            this.userS = user;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel", conUsername, conPass);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stmt2 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            getDays();
//            setupToggle();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAvailable = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        pnlSeats = new javax.swing.JPanel();
        tglT1 = new javax.swing.JToggleButton();
        tglT2 = new javax.swing.JToggleButton();
        tglT3 = new javax.swing.JToggleButton();
        tglT4 = new javax.swing.JToggleButton();
        tglT5 = new javax.swing.JToggleButton();
        tglT6 = new javax.swing.JToggleButton();
        tglT7 = new javax.swing.JToggleButton();
        tglT8 = new javax.swing.JToggleButton();
        cmbSlotTime = new javax.swing.JComboBox<>();
        cmbDates = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCheckAnotherDate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Table Booking");

        btnAvailable.setText("Show Available Tables");
        btnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableActionPerformed(evt);
            }
        });

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        pnlSeats.setBackground(new java.awt.Color(255, 204, 204));

        tglT1.setText("Table 1");

        tglT2.setText("Table 2");

        tglT3.setText("Table 3");

        tglT4.setText("Table 4");

        tglT5.setText("Table 5");

        tglT6.setText("Table 6");
        tglT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglT6ActionPerformed(evt);
            }
        });

        tglT7.setText("Table 7");

        tglT8.setText("Table 8");

        javax.swing.GroupLayout pnlSeatsLayout = new javax.swing.GroupLayout(pnlSeats);
        pnlSeats.setLayout(pnlSeatsLayout);
        pnlSeatsLayout.setHorizontalGroup(
            pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeatsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSeatsLayout.createSequentialGroup()
                        .addComponent(tglT5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglT6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglT7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglT8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSeatsLayout.createSequentialGroup()
                        .addComponent(tglT1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglT2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglT3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglT4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlSeatsLayout.setVerticalGroup(
            pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeatsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglT1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglT2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglT3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglT4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglT5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglT6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglT7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglT8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        cmbDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDatesActionPerformed(evt);
            }
        });

        jLabel2.setText("Dates");

        jLabel3.setText("Slots");

        btnCheckAnotherDate.setText("Check Another Date");
        btnCheckAnotherDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnotherDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbSlotTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDates, 0, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvailable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckAnotherDate)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBook)
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAvailable)
                            .addComponent(btnCheckAnotherDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSlotTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(25, 25, 25)
                .addComponent(pnlSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnBook)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupToggle()
    {
        tglT1.setSelected(false);
        tglT1.setEnabled(true);
        tglT2.setSelected(false);
        tglT2.setEnabled(true);
        tglT3.setSelected(false);
        tglT3.setEnabled(true);
        tglT4.setSelected(false);
        tglT4.setEnabled(true);
        tglT5.setSelected(false);
        tglT5.setEnabled(true);
        tglT6.setSelected(false);
        tglT6.setEnabled(true);
        tglT7.setSelected(false);
        tglT7.setEnabled(true);
        tglT8.setSelected(false);
        tglT8.setEnabled(true);
    }
    private void getDays()
    {
        String q = "call getdistinctdates()";
        
        try{
            rs2 = stmt2.executeQuery(q);
            
            while(rs2.next())
            {   
                cmbDates.addItem(rs2.getString("date"));
            }
           
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void tglT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglT6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglT6ActionPerformed

    private void btnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableActionPerformed
        pnlSeats.setVisible(true);
        cmbDates.setEnabled(false);
        cmbSlotTime.setEnabled(false);
        String date = cmbDates.getSelectedItem().toString();
        String time = cmbSlotTime.getSelectedItem().toString();
        setupToggle();
        ArrayList<String> bookList = new ArrayList<String>();
        
        String query = "call getbookedtablenumber('"+date+"', '"+time+"')";
        
        try
        {
            rs = stmt.executeQuery(query);
            
            while(rs.next())
            {
                bookList.add(rs.getString("table_number"));
            }
            
            if(bookList.contains("1"))
            {
                tglT1.setEnabled(false);
            }
            if(bookList.contains("2"))
            {
                tglT2.setEnabled(false);
            }
            if(bookList.contains("3"))
            {
                tglT3.setEnabled(false);
            }
            if(bookList.contains("4"))
            {
                tglT4.setEnabled(false);
            }
            if(bookList.contains("5"))
            {
                tglT5.setEnabled(false);
            }
            if(bookList.contains("6"))
            {
                tglT6.setEnabled(false);
            }
            if(bookList.contains("7"))
            {
                tglT7.setEnabled(false);
            }
            if(bookList.contains("8"))
            {
                tglT8.setEnabled(false);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
            
    }//GEN-LAST:event_btnAvailableActionPerformed

    private void cmbDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDatesActionPerformed
        // TODO add your handling code here:
        
        try {

            String q2 = cmbDates.getSelectedItem().toString();

            String q3 = "call getslotsbydate('" + q2 + "')";
            DefaultComboBoxModel model2 = new DefaultComboBoxModel();
            model2 = (DefaultComboBoxModel) cmbSlotTime.getModel();
            model2.removeAllElements();

            rs = stmt.executeQuery(q3);

            while (rs.next()) {
                model2.addElement(rs.getString("timeslot"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmbDatesActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        try
        {
            ArrayList<String> bookList = new ArrayList<String>();
            
            if(tglT1.isSelected())
            {
                bookList.add("1");
            }
            if(tglT2.isSelected())
            {
                bookList.add("2");
            }
            if(tglT3.isSelected())
            {
                bookList.add("3");
            }
            if(tglT4.isSelected())
            {
                bookList.add("4");
            }
            if(tglT5.isSelected())
            {
                bookList.add("5");
            }
            if(tglT6.isSelected())
            {
                bookList.add("6");
            }
            if(tglT7.isSelected())
            {
                bookList.add("7");
            }
            if(tglT8.isSelected())
            {
                bookList.add("8");
            }
            
            String time = cmbSlotTime.getSelectedItem().toString();
            String date = cmbDates.getSelectedItem().toString();
            
            for(int i = 0; i<bookList.size(); i++)
            {
                String tableno = bookList.get(i);
                
                String query = "call bookslot('"+this.userS+"', "+tableno+", '"+date+"', '"+time+"')";
                stmt.executeUpdate(query);
                
                JOptionPane.showMessageDialog(null, "Successfully Booked!");
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnCheckAnotherDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnotherDateActionPerformed
        
        pnlSeats.setVisible(false);
        cmbDates.setEnabled(true);
        cmbSlotTime.setEnabled(true);
    }//GEN-LAST:event_btnCheckAnotherDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailable;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCheckAnotherDate;
    private javax.swing.JComboBox<String> cmbDates;
    private javax.swing.JComboBox<String> cmbSlotTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlSeats;
    private javax.swing.JToggleButton tglT1;
    private javax.swing.JToggleButton tglT2;
    private javax.swing.JToggleButton tglT3;
    private javax.swing.JToggleButton tglT4;
    private javax.swing.JToggleButton tglT5;
    private javax.swing.JToggleButton tglT6;
    private javax.swing.JToggleButton tglT7;
    private javax.swing.JToggleButton tglT8;
    // End of variables declaration//GEN-END:variables
}
