/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author abhinavdholi
 */
public class CustomerMainPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMainPage
     */
    String conUser;
    String conPass;
    String userS;
    
    public CustomerMainPage(String username, String password, String user) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lblWelcome.setText("Welcome "+user);
        this.conPass = password;
        this.conUser = username;
        this.userS = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuBookTable = new javax.swing.JMenuItem();
        mnuOrderFood = new javax.swing.JMenuItem();
        mnuShowMyBills = new javax.swing.JMenuItem();
        mnuSignout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblWelcome.setText("Welcome");

        jMenu1.setText("Options");

        mnuBookTable.setText("Book a Table");
        mnuBookTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBookTableActionPerformed(evt);
            }
        });
        jMenu1.add(mnuBookTable);

        mnuOrderFood.setText("Order Food");
        mnuOrderFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOrderFoodActionPerformed(evt);
            }
        });
        jMenu1.add(mnuOrderFood);

        mnuShowMyBills.setText("Show My Orders");
        mnuShowMyBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuShowMyBillsActionPerformed(evt);
            }
        });
        jMenu1.add(mnuShowMyBills);

        mnuSignout.setText("Sign Out");
        mnuSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSignoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSignout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblWelcome)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuBookTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBookTableActionPerformed
        BookingForm frmBook = new BookingForm(conUser, conPass, userS);
        frmBook.setVisible(true);
    }//GEN-LAST:event_mnuBookTableActionPerformed

    private void mnuOrderFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOrderFoodActionPerformed
        OrderFoodForm custForm = new OrderFoodForm(conUser, conPass, userS);
        custForm.setVisible(true);
    }//GEN-LAST:event_mnuOrderFoodActionPerformed

    private void mnuShowMyBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuShowMyBillsActionPerformed
        ShowMyBillsForm frmBills = new ShowMyBillsForm(conUser, conPass, userS);
        frmBills.setVisible(true);
    }//GEN-LAST:event_mnuShowMyBillsActionPerformed

    private void mnuSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSignoutActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Sure you want to sign out?");
        
        if (i==0)
        {
            this.dispose();
        }
    }//GEN-LAST:event_mnuSignoutActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuItem mnuBookTable;
    private javax.swing.JMenuItem mnuOrderFood;
    private javax.swing.JMenuItem mnuShowMyBills;
    private javax.swing.JMenuItem mnuSignout;
    // End of variables declaration//GEN-END:variables
}
