/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhinavdholi
 */
public class ShowMyBillsForm extends javax.swing.JFrame {

     Connection con;
    ResultSet rs;
    Statement stmt;
    String conUsername;
    String conPass;
    String userS;
    public ShowMyBillsForm(String username, String password, String user) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        try {
            this.conUsername = username;
            this.conPass = password;
            this.userS = user;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel", conUsername, conPass);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            
            lblOrderHist.setText(userS+"'s Order History");
            
            showOrderHistory();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblOrderHist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Tax", "Total Amount", "Payment Method"
            }
        ));
        jScrollPane1.setViewportView(tblOrders);

        lblOrderHist.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblOrderHist.setText("Your Order History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblOrderHist)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblOrderHist)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showOrderHistory()
    {
        String q = "call displayordersbyusername('"+ this.userS +"')";
        
        try
        {
            rs = stmt.executeQuery(q);
            
            DefaultTableModel m = (DefaultTableModel)tblOrders.getModel();
            
            
            int rcount = tblOrders.getRowCount();
            
            for (int i =0; i<rcount;i++)
            {
               m.removeRow(0);
            }
            String orderid,tax,amt,payment;
            
             while (rs.next())
                {
                    orderid = rs.getString("order_id");
                    tax = rs.getString("total_tax");
                    amt = rs.getString("total_amount");
                    payment = rs.getString("payment_method");
                    
                    m.addRow(new Object[]{orderid, tax, amt, payment});    
                }
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderHist;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
