/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author abhinavdholi
 */
public class StaffMainPage extends javax.swing.JFrame {

    /**
     * Creates new form StaffMainPage
     */
    String conUser;
    String conPass;
    String userS;
    public StaffMainPage(String username, String password, String user) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lblWelcome.setText("Welcome "+user);
        this.conPass = password;
        this.conUser = username;
        this.userS = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOptions = new javax.swing.JMenu();
        mnuSlot = new javax.swing.JMenuItem();
        mnuBooking = new javax.swing.JMenuItem();
        mnuMenu = new javax.swing.JMenuItem();
        mnuSignOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome");

        mnuOptions.setText("Options");

        mnuSlot.setText("Slot Management");
        mnuSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSlotActionPerformed(evt);
            }
        });
        mnuOptions.add(mnuSlot);

        mnuBooking.setText("Show Bookings");
        mnuBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBookingActionPerformed(evt);
            }
        });
        mnuOptions.add(mnuBooking);

        mnuMenu.setText("Menu Management");
        mnuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMenuActionPerformed(evt);
            }
        });
        mnuOptions.add(mnuMenu);

        mnuSignOut.setText("Sign out");
        mnuSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSignOutActionPerformed(evt);
            }
        });
        mnuOptions.add(mnuSignOut);

        jMenuBar1.add(mnuOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lblWelcome)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lblWelcome)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBookingActionPerformed
        ShowAllBookingsForm frmBook = new ShowAllBookingsForm(conUser, conPass);
        frmBook.setVisible(true);
    }//GEN-LAST:event_mnuBookingActionPerformed

    private void mnuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMenuActionPerformed
        // TODO add your handling code here:
        MenuOptionsFrame menuOptionsFrame = new MenuOptionsFrame(this.conUser,this.conPass);
        menuOptionsFrame.setVisible(true);
        
        
    }//GEN-LAST:event_mnuMenuActionPerformed

    private void mnuSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSlotActionPerformed
        SlotManagementForm sltForm = new SlotManagementForm(conUser, conPass, userS);
        sltForm.setVisible(true);
    }//GEN-LAST:event_mnuSlotActionPerformed

    private void mnuSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSignOutActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Sure you want to sign out?");
        
        if (i==0)
        {
            this.dispose();
        }
    }//GEN-LAST:event_mnuSignOutActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuItem mnuBooking;
    private javax.swing.JMenuItem mnuMenu;
    private javax.swing.JMenu mnuOptions;
    private javax.swing.JMenuItem mnuSignOut;
    private javax.swing.JMenuItem mnuSlot;
    // End of variables declaration//GEN-END:variables
}
